services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  todo-service:
    build: todo-service
    container_name: todo-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    env_file:
      - .env.todo

  gateway-service:
    build: gateway-service
    container_name: gateway-service
    depends_on:
      - todo-service
    ports:
      - "8080:8080"
    env_file:
      - .env.gateway

volumes:
  pgdata:
